</body>
</html>
/* Reset */
*[+] {margin: 0;[/+][-] {[/-]
[+]padding:[/+][-] margin:[/-] 0;
[+]box-sizing: border-box}[/+][-] padding: 0;[/-]
[-] box-sizing: border-box;[/-]
[+]body {font-family: 'Arial', sans-serif;[/+][-] }[/-]
[+] line-height: 1.6;[/+]
[+]color: #333}[/+][-] body {[/-]
[-] font-family: 'Arial', sans-serif;[/-]
[+]/* Header */[/+][-] line-height: 1.6;[/-]
[+]header {background: #0056b3;[/+][-] color: #333;[/-]
[+]color: white;[/+][-] }[/-]
[+] padding: 1rem;[/+]
[+]text-align: center;}[/+][-] /* Header */[/-]
[-]header {[/-]
[+]nav ul {list-style: none;[/+][-] background: #0056b3;[/-]
[+]display: flex;[/+][-] color: white;[/-]
[+]justify-content: center;[/+][-] padding: 1rem;[/-]
[+]gap: 20px;[/+][-] text-align: center;[/-]
[+]margin-top: 10px;}[/+][-] }[/-]
nav[+] a {color: white;[/+][-] ul {[/-]
[+]text-decoration:[/+][-] list-style:[/-] none;
[+]font-weight: bold;}[/+][-] display: flex;[/-]
[-] justify-content: center;[/-]
[+]/* Hero */[/+][-] gap: 20px;[/-]
[+].hero {background: #e6f0ff;[/+][-] margin-top: 10px;[/-]
[+]padding: 3rem;[/+][-] }[/-]
[+] text-align: center;}[/+]
[+]/* Produktet */[/+][-] nav a {[/-]
[+].products {padding: 2rem;}[/+][-] color: white;[/-]
[-] text-decoration: none;[/-]
[+].product-grid [/+][-] font-weight: bold;[/-]
[+]{display: grid;[/+][-] }[/-]
[+] grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));[/+]
[+]gap: 20px;[/+][-] /* Hero */[/-]
[+]margin-top: 20px;}[/+][-] .hero {[/-]
[-] background: #e6f0ff;[/-]
[+].product-card [/+][-] padding: 3rem;[/-]
[+]{border: 1px solid #ddd;[/+][-] text-align: center;[/-]
[+]border-radius: 8px;[/+][-] }[/-]
[+] padding: 1rem;[/+]
[+]text-align: center;[/+][-] /* Produktet */[/-]
[+]transition: transform 0.3s;}[/+][-] .products {[/-]
[-] padding: 2rem;[/-]
[+].product-card:hover {transform: translateY(-5px);[/+][-] }[/-]
[+] box-shadow: 0 5px 15px rgba(0, 86, 179, 0.1);}[/+]
[-].product-grid {[/-]
[+].product-card img [/+][-] display: grid;[/-]
[+]{width: 100%;[/+][-] grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));[/-]
[+]height: 180px;[/+][-] gap: 20px;[/-]
[+]object-fit: cover;[/+][-] margin-top: 20px;[/-]
[+]border-radius: 5px;}[/+][-] }[/-]
[+].product-btn [/+][-] .product-card {[/-]
[+]{background: #0056b3;[/+][-] border: 1px solid #ddd;[/-]
[+]color: white;[/+][-] border-radius: 8px;[/-]
[+]border: none;[/+][-] padding: 1rem;[/-]
[+]padding: 8px 16px;[/+][-] text-align: center;[/-]
[+]border-radius: 4px;[/+][-] transition: transform 0.3s;[/-]
[+]margin-top: 10px;[/+][-] }[/-]
[+] cursor: pointer;}[/+]
[-].product-card:hover {[/-]
[+]/* Kontakt */[/+][-] transform: translateY(-5px);[/-]
[+].contact [/+][-] box-shadow: 0 5px 15px rgba(0, 86, 179, 0.1);[/-]
[+]{background: #f9f9f9;[/+][-] }[/-]
[+] padding: 2rem;[/+]
[+]text-align: center;}[/+][-] .product-card img {[/-]
[-] width: 100%;[/-]
[+]/* Footer */[/+][-] height: 180px;[/-]
[+]footer [/+][-] object-fit: cover;[/-]
[+]{background: #333;[/+][-] border-radius: 5px;[/-]
[+]color: white;[/+][-] }[/-]
[+] text-align: center;[/+]
[+]padding: 1rem;}[/+][-] .product-btn {[/-]
[-] background: #0056b3;[/-]
[+]// Function for products buttons [/+][-] color: white;[/-]
[+]document.querySelectorAll('.product-btn').forEach(button => {button.addEventListener('click', () => [/+][-] border: none;[/-]
[+]{const productName = button.parentElement.querySelector('h3').textContent;[/+][-] padding: 8px 16px;[/-]
[+]alert(`Ju keni zgjedhur: ${productName}\n(This can be changed to the new tab or new page )`);});[/+][-] border-radius: 4px;[/-]
[+]});[/+][-] margin-top: 10px;[/-]
[-] cursor: pointer;[/-]
[+]// change colour when is scrolled [/+][-] }[/-]
[+]window.addEventListener('scroll', () => [/+]
[+]{const header = document.querySelector('header');[/+][-] /* Kontakt */[/-]
[+]header.style.backgroundColor = window.scrollY > 50 ? '#003d82' : '#0056b3';});[/+][-] .contact {[/-]
[-] background: #f9f9f9;[/-]
[-] padding: 2rem;[/-]
[-] text-align: center;[/-]
[-]}[/-]
[-]/* Footer */[/-]
[-]footer {[/-]
[-] background: #333;[/-]
[-] color: white;[/-]
[-] text-align: center;[/-]
[-] padding: 1rem;[/-]
[-]}[/-]
[-]// Function for products buttons [/-]
[-]document.querySelectorAll('.product-btn').forEach(button => {[/-]
[-] button.addEventListener('click', () => {[/-]
[-] const productName = button.parentElement.querySelector('h3').textContent;[/-]
[-] alert(`Ju keni zgjedhur: ${productName}\n(This can be changed to the new tab or new page )`);[/-]
[-] });[/-]
[-]});[/-]
[-]// change colour when is scrolled [/-]
[-]window.addEventListener('scroll', () => {[/-]
[-] const header = document.querySelector('header');[/-]
[-] header.style.backgroundColor = window.scrollY > 50 ? '#003d82' : '#0056b3';[/-]
[-]});